config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]

  resources :ingredients, only: [:index, :new, :create, :destroy]

  root "cocktails#index"

  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  # cloudinary + attachinary
  has_attachment :photo, accept: [:jpg]
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail_id,
            uniqueness: { scope: :ingredient_id,
                          message: "This cocktail already has a dose with this
                          ingredient" }

  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses, dependent: :restrict_with_exception
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy

    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [:new, :create]

  # new is useless but it is required by rake
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to ingredients_path
    else
      render :new
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.destroy
      redirect_to ingredients_path
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :attachinary %>

        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="container padded">
  <div class="row">

    <% if @cocktails.length > 0 %>
      <% @cocktails.each do |cocktail| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-position: center ; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(
          <% if cocktail.photo? %>
          <%= cloudinary_url(cocktail.photo.path) %>
          <% end %>);">
            <!-- <div class="card-category"></div> -->
            <div class="card-description">
              <h2><%= cocktail.name %></h2>
            </div>
            <%= link_to "", cocktail_path(cocktail), class: "card-link"%>
            </div>
        </div>
      <% end %>
    <% else %>
      <p>No cocktails in the database</p>
    <% end %>

  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :attachinary %>

        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(50,50,50,0.6) 50%), url(
          <% if @cocktail.photo? %>
          <%= cloudinary_url(@cocktail.photo.path) %>
          <% end %>); background-position: center;">
  <div class="banner-content">
    <h1><%= @cocktail.name %></h1>
    <ul>
      <% @cocktail.doses.each do |dose| %>
        <li><%= dose.description %> <%= dose.ingredient.name %> <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, dose_path(dose), method: :delete, data: { confirm: "Are you sure ?" } %>  </li>
      <% end %>
    </ul>

  </div>
</div>


<%= link_to "Edit", edit_cocktail_path %>
<%= link_to "Delete", cocktail_path, method: :delete %>

<%= simple_form_for ([ @cocktail, Dose.new ]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit %>
<% end %>

app/views/doses/new.html.erb
<%= simple_form_for ([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>

  <%= f.button :submit %>
<% end %>

app/views/ingredients/index.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <ul>
        <% @ingredients.each do |ingredient| %>
          <li><%= ingredient.name %> - <%= link_to "delete", ingredient_path(ingredient), method: :delete, data: { confirm: "Are you sure ?" %></li>
        <% end %>
      </ul>
      <%= link_to "Add an ingredient", new_ingredient_path %>
    </div>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= simple_form_for @ingredient do |f| %>
        <%= f.input :name %>

        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Drop the ugly navbar -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Add a new cocktail", new_cocktail_path %></li>
        <li>---</li>
        <li><%= link_to "List ingredients", ingredients_path %></li>
        <li><%= link_to "Add an ingredient", new_ingredient_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>

      <%= render partial: "shared/navbar" %>
      <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "puke.jpg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Add a new cocktail", new_cocktail_path %></li>
        <li>---</li>
        <li><%= link_to "List ingredients", ingredients_path %></li>
        <li><%= link_to "Add an ingredient", new_ingredient_path %></li>
      </ul>
    </div>
  </div>
</div>